### ISSUE TITLE
pgsql + yaml order respect

### ISSUE THREAD

**Issue by sumia01** [romanyx/polluter#10]
Hi, 

the problem in your previous issue #3  is still exists with pgsql + yaml.
The input order kept with pg + json.
Here is the input and the command slice output

IN: 
```
member:
    - id: 1
member_role:
    - id: 1
member_token:
    - id: 1
messenger_application:
    - id: 1
organization:
    - id: 1
bot:
    - id: 1
      organization_id: 1
```

OUT: 
```
INSERT INTO bot ...
INSERT INTO member ... 
INSERT INTO member_role ...
INSERT INTO member_token ...
INSERT INTO messenger_application ...
INSERT INTO organization ...
```

The problem is with j, err := yaml.YAMLToJSON(data) in yaml.go, after this conversion the output is in alphabetical order.
